# -*- coding: utf-8 -*-
"""AlgoProgr_Mod4_Camila.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l28vKA4kaqKJpyZG0tsCHWNfnQ1F-_lJ
"""

#cadastro do produto, rece o numero de produtos
#usa uma linha linear
#verifica duplicatas
#Se já existir o produto irá aparecer a mensagem "Produto já cadastrado"
#Se não existir adiciona o nome e o preço
def cadastrar_produtos(n):
    lista = []
    for _ in range(n):
        nome = input().strip()
        preco = float(input().strip())
        if nome in lista[::2]:  # pega só os nomes (índices pares)
            print("Produto já cadastrado")
        else:
            lista.append(nome)
            lista.append(preco)
    return lista

# Lê nomes até usuario digitar Fim
#Se encontar o nome imprime o preço
#Caso o contrario exibe a mensagem "Produto não cadastrado"
def buscar_precos(lista):
    while True:
        produto = input().strip()
        if produto == "Fim":
            break
        if produto in lista[::2]:
            indice = lista.index(produto)
            print(lista[indice + 1])
        else:
            print("Produto não cadastrado")


# Função Principal, lê n, cadastra os produtos e chama a busca
def main():
    n = int(input().strip())
    lista = cadastrar_produtos(n)
    buscar_precos(lista)


if __name__ == "__main__":
    main()